export const REDUCER_CONSTANT = {
  LOADER_START: "LOADER_START",
  LOADER_OFF: "LOADER_OFF",
  USER_SIGNIN: "USER_SIGNIN",
  STORE_OPEN: "STORE_OPEN",
  STORE_CLOSE: "STORE_CLOSE",
  REGISTER_OPEN: "REGISTER_OPEN",
  REGISTER_CLOSE: "REGISTER_CLOSE",
  TILL_OPEN: "TILL_OPEN",
  TILL_CLOSE: "TILL_CLOSE",
  GET_INFO: 'GET_INFO',
  ARTICLES: {
    GET_ALL_ARTICLES: "ARTICLES/GET_ALL_ARTICLES",
    ADD_ARTICLE: "ARTICLES/ADD_ARTICLE"
  },
  CHECKOUT_ARTICLES: {
    GET_ARTICLE: 'CHECKOUT_ARTICLES/GET_ARTICLE',
  },
  CART_ARTICLES: {
    GET_ALL_CART_ARTICLES: "CART_ARTICLES/GET_ALL_CART_ARTICLE"
  },
  CHECKOUT_TOTAL: {
    SET_CHECKOUT_TOTAL: "CHECKOUT_TOTAL/SET_CHECKOUT_TOTAL",
    GET_CHECKOUT_TOTAL: 'CHECKOUT_TOTAL/GET_CHECKOUT_TOTAL'
  }
};
